In [4]:
#this is what handles arrays, import it as an easy name to call it
import numpy as np
#1D Tensor aka row vector...not that useful
x=np.array([1])
print('1D',x.ndim)
#2D Tensor aka Matrix.....p important
y=np.array([[1,2,3,4],[5,6,7,8]])
print('2D',y.ndim)
#3D Tensor aka a Matrix of matrices....also p important
z=np.array([[[1,2,3],[11,12,13]],[[4,5,6],[24,25,26]]])
print('3D',z.ndim)
z1=np.array([[[1,2,3]],[[4,5,6]]])
print('z1',z1.ndim)
z2=np.array([[[1,2,3]]])
print('z2',z2.ndim)

('1D', 1)
('2D', 2)
('3D', 3)
('z1', 3)
('z2', 3)


In [8]:
#Shape=( #of matrices, #of rows per matrix, #of elements in each row vec.)
print('z',z.shape)
print('z1',z1.shape)
print('z2',z2.shape)

('z', (2, 2, 3))
('z1', (2, 1, 3))
('z2', (1, 1, 3))


In [25]:
print(z)
#z has 2 matrices with 2 rows each with 3 elements
print(z1)
#z1 has 2 matrices with 1 row each with 3 elem.
print(z2)
#z2 has 1 matrix with 1 row with 3 elem.

[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [24 25 26]]]
[[[1 2 3]]

 [[4 5 6]]]
[[[1 2 3]]]
